import type { PortfolioEntry } from './types';

export const portfolioEntries: PortfolioEntry[] = [
  {
    slug: 'public-forum-operations',
    category: '설치사례 Placeholder',
    tags: ['포럼 및 설명회'],
    title: '기관 포럼 운영 사례',
    description: '기관 행사에 맞춘 홈페이지, 참가자 응대, 현장 등록, 운영 인력 배치 예시를 넣을 수 있습니다.',
    outcome: '실제 행사명, 일정, 규모, 운영 결과는 추후 직접 입력',
    client: '기관명 Placeholder',
    period: '2026.00 Placeholder',
    scope: ['행사 운영 기획', '현장 등록/응대', '결과 정리'],
    summary: '이 사례에는 행사 개요와 목표를 2~3문장으로 입력하면 됩니다.',
    challenge: '고객이 어떤 문제를 갖고 있었는지 또는 어떤 요청을 했는지 입력하면 됩니다.',
    approach: '마이스파트너가 어떤 방식으로 운영 구조를 잡고 실행했는지 입력하면 됩니다.',
    result: '행사 결과, 운영 성과, 고객 반응, 다음 과제 등을 입력하면 됩니다.',
    galleryPlaceholders: ['대표 사진 Placeholder', '현장 사진 Placeholder', '결과 자료 Placeholder'],
  },
  {
    slug: 'seminar-checkin-support',
    category: '포트폴리오 Placeholder',
    tags: ['학회 및 세미나', '현장 등록 및 체크인'],
    title: '학회 및 세미나 운영 사례',
    description: '학회/세미나 유형에 맞춘 연사 안내, 현장 체크인, 세션 운영 사례를 소개할 수 있습니다.',
    outcome: '실제 사진, 고객사명, 행사 성과 수치는 추후 직접 입력',
    client: '학회/협회명 Placeholder',
    period: '2026.00 Placeholder',
    scope: ['안내 페이지 구성', '체크인 지원', '세션 운영 보조'],
    summary: '이 사례에는 학회 또는 세미나의 성격과 운영 범위를 입력하면 됩니다.',
    challenge: '현장 운영에서 중요했던 포인트나 요구사항을 입력하면 됩니다.',
    approach: '연사/세션 안내, 등록 흐름, 현장 응대 방식 등을 입력하면 됩니다.',
    result: '참가자 반응, 운영 효율, 정리 결과 등을 입력하면 됩니다.',
    galleryPlaceholders: ['연사 안내 이미지 Placeholder', '등록 데스크 Placeholder', '세션 운영 Placeholder'],
  },
  {
    slug: 'vip-invitation-event',
    category: '현장사례 Placeholder',
    tags: ['기업 초청 행사'],
    title: '기업 초청 행사 운영 사례',
    description: '초청 대상 관리, 현장 응대, 진행 운영, 사후 정리까지 어떤 범위를 담당했는지 보여줄 수 있습니다.',
    outcome: '실제 담당 범위와 결과 요약은 추후 직접 입력',
    client: '기업명 Placeholder',
    period: '2026.00 Placeholder',
    scope: ['초청 대상 관리', '현장 응대', '사후 자료 정리'],
    summary: '이 사례에는 기업 행사 성격과 운영 범위를 입력하면 됩니다.',
    challenge: 'VIP 응대, 일정 관리, 현장 동선 등 핵심 난점을 입력하면 됩니다.',
    approach: '초청부터 현장 운영까지 어떤 프로세스로 대응했는지 입력하면 됩니다.',
    result: '행사 종료 후 정리 결과와 고객 피드백을 입력하면 됩니다.',
    galleryPlaceholders: ['행사 메인컷 Placeholder', '현장 응대 Placeholder', '결과 보고 Placeholder'],
  },
];

export const portfolioCategories = [
  '포럼 및 설명회',
  '학회 및 세미나',
  '기업 초청 행사',
  '전시/부스 운영',
  '현장 등록 및 체크인',
];
